_commit: c5049a9
_src_path: gh:adrn-blog/template
day: 3
month: 6
python_version: '3.10'
slug: matplotlib-transparent-animation
title: Making a Matplotlib animation with a transparent background
year: 2016
