name: Build post

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute:
    runs-on: ubuntu-latest
    concurrency: post-${{ github.ref }}
    steps:
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - uses: adrn-blog/execute-post@main
        with:
          python-version: "3.10"
